name: Java CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 8, 11 ]
        experimental: [ false ]
#        include:
#          - java: 18-ea
#            os: ubuntu-latest
#            experimental: true

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -V --no-transfer-progress clean test
